# Generated by Django 2.2.3 on 2019-08-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190815_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='test product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('d', 'Deserts'), ('p', 'Pizza'), ('c', 'Cold Drinks')], max_length=1),
        ),
    ]
