# Generated by Django 2.2.3 on 2019-08-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190815_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('c', 'Cold Drinks'), ('d', 'Deserts'), ('p', 'Pizza')], max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('d', 'danger'), ('s', 'secondary'), ('p', 'primary')], max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='test-product'),
        ),
    ]
