# Generated by Django 2.2.3 on 2019-08-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190815_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Test description aslkdjhalsdhakjs  daksjdb anksjdaskdj askdj aksdj kajsd aksdj askjd'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('p', 'Pizza'), ('c', 'Cold Drinks'), ('d', 'Deserts')], max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('d', 'danger'), ('p', 'primary'), ('s', 'secondary')], max_length=1),
        ),
    ]
